### PR TITLE
Fix/code quality

### PR DESCRIPTION
**Pull request by zzjc1234**
This pull request fix the illegal filename.

### CODE REVIEW

**Comment by linsyking** [comment]
I guess we need to minimize the dependency.

I will look into this later.

**Comment by zzjc1234** [comment]
@linsyking It seems that the build test doesn't support the werkzeug module

**Comment by linsyking** [comment]
> @linsyking It seems that the build test doesn't support the werkzeug module

Yes, we don't want to add that module

**Comment by zzjc1234** [comment]
The code has been tested locally and the required functions seem to work well.

**Pull request merged**
